-- MySQL Script generated by MySQL Workbench
-- Tue Apr  1 09:12:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vuelos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vuelos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vuelos` ;
USE `vuelos` ;

-- -----------------------------------------------------
-- Table `vuelos`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`ubicaciones` (
  `id_ubicacion` INT NOT NULL,
  `ciudad` VARCHAR(70) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_ubicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`aeropuertos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`aeropuertos` (
  `id_aeropuerto` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo_iata` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_ubicaciones` INT NOT NULL,
  PRIMARY KEY (`id_aeropuerto`),
  INDEX `fk_aeropuertos_ubicaciones1_idx` (`id_ubicaciones` ASC) VISIBLE,
  CONSTRAINT `fk_aeropuertos_ubicaciones1`
    FOREIGN KEY (`id_ubicaciones`)
    REFERENCES `vuelos`.`ubicaciones` (`id_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`estado_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`estado_reserva` (
  `id_estado_reserva` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_estado_reserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL,
  `nombre_tipo` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`usuarios` (
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_tipo_usuario1_idx` (`tipo_usuario_id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id_tipo_usuario`)
    REFERENCES `vuelos`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`reservas` (
  `id_reserva` INT NOT NULL,
  `fecha_hora_reserva` DATETIME NOT NULL,
  `cantidad_pasajeros` INT NOT NULL,
  `costo_total` INT NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_estado_reserva` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reservas_estado_reserva1_idx` (`id_estado_reserva` ASC) VISIBLE,
  INDEX `fk_reservas_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_estado_reserva1`
    FOREIGN KEY (`id_estado_reserva`)
    REFERENCES `vuelos`.`estado_reserva` (`id_estado_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `vuelos`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`estado_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`estado_asiento` (
  `id_estado_asiento` INT NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_estado_asiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`clase_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`clase_asiento` (
  `id_clase_asiento` INT NOT NULL,
  `tipo_clase` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_clase_asiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`asientos` (
  `id_asiento` INT NOT NULL,
  `numero_asiento` INT NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `reservas_id_reserva` INT NOT NULL,
  `id_estado_asiento` INT NOT NULL,
  `id_clase_asiento` INT NOT NULL,
  PRIMARY KEY (`id_asiento`),
  INDEX `fk_asientos_reservas1_idx` (`reservas_id_reserva` ASC) VISIBLE,
  INDEX `fk_asientos_estado_asiento1_idx` (`id_estado_asiento` ASC) VISIBLE,
  INDEX `fk_asientos_clase_asiento1_idx` (`id_clase_asiento` ASC) VISIBLE,
  CONSTRAINT `fk_asientos_reservas1`
    FOREIGN KEY (`reservas_id_reserva`)
    REFERENCES `vuelos`.`reservas` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asientos_estado_asiento1`
    FOREIGN KEY (`id_estado_asiento`)
    REFERENCES `vuelos`.`estado_asiento` (`id_estado_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asientos_clase_asiento1`
    FOREIGN KEY (`id_clase_asiento`)
    REFERENCES `vuelos`.`clase_asiento` (`id_clase_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`vuelos` (
  `id_vuelo` INT NOT NULL,
  `numero_vuelo` VARCHAR(40) NOT NULL,
  `aerolinea` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_origen` INT NOT NULL,
  `id_destino` INT NOT NULL,
  PRIMARY KEY (`id_vuelo`),
  INDEX `fk_vuelos_aeropuertos_idx` (`id_origen` ASC) VISIBLE,
  INDEX `fk_vuelos_aeropuertos1_idx` (`id_destino` ASC) VISIBLE,
  CONSTRAINT `fk_vuelos_aeropuertos`
    FOREIGN KEY (`id_origen`)
    REFERENCES `vuelos`.`aeropuertos` (`id_aeropuerto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelos_aeropuertos1`
    FOREIGN KEY (`id_destino`)
    REFERENCES `vuelos`.`aeropuertos` (`id_aeropuerto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`vuelos_programados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`vuelos_programados` (
  `id_vuelo_programado` INT NOT NULL,
  `fecha_hora_salida` DATETIME NOT NULL,
  `fecha_hora_llegada` DATETIME NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_vuelo` INT NOT NULL,
  PRIMARY KEY (`id_vuelo_programado`),
  INDEX `fk_vuelos_programados_vuelos1_idx` (`id_vuelo` ASC) VISIBLE,
  CONSTRAINT `fk_vuelos_programados_vuelos1`
    FOREIGN KEY (`id_vuelo`)
    REFERENCES `vuelos`.`vuelos` (`id_vuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`escalas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`escalas` (
  `id_escala` INT NOT NULL,
  `fecha_hora_llegada` DATETIME NOT NULL,
  `fecha_hora_salida` DATETIME NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_aeropuertos` INT NOT NULL,
  `id_vuelo_programado` INT NOT NULL,
  PRIMARY KEY (`id_escala`, `id_aeropuertos`, `id_vuelo_programado`),
  INDEX `fk_escalas_aeropuertos1_idx` (`id_aeropuertos` ASC) VISIBLE,
  INDEX `fk_escalas_vuelos_programados1_idx` (`id_vuelo_programado` ASC) VISIBLE,
  CONSTRAINT `fk_escalas_aeropuertos1`
    FOREIGN KEY (`id_aeropuertos`)
    REFERENCES `vuelos`.`aeropuertos` (`id_aeropuerto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escalas_vuelos_programados1`
    FOREIGN KEY (`id_vuelo_programado`)
    REFERENCES `vuelos`.`vuelos_programados` (`id_vuelo_programado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vuelos`.`reservas_vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`reservas_vuelos` (
  `id_reserva_vuelo` INT NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_vuelo_programado` INT NOT NULL,
  `id_reserva` INT NOT NULL,
  PRIMARY KEY (`id_reserva_vuelo`),
  INDEX `fk_reservas_vuelos_vuelos_programados1_idx` (`id_vuelo_programado` ASC) VISIBLE,
  INDEX `fk_reservas_vuelos_reservas1_idx` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_vuelos_vuelos_programados1`
    FOREIGN KEY (`id_vuelo_programado`)
    REFERENCES `vuelos`.`vuelos_programados` (`id_vuelo_programado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_vuelos_reservas1`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `vuelos`.`reservas` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
