-- MySQL Script generated by MySQL Workbench
-- Wed Mar 26 12:59:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
-- -----------------------------------------------------
-- Schema agendaviajes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agendaviajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agendaviajes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuarios` (
  `ID_tipo_usuario` INT NOT NULL,
  `tipo_estudiante` INT NOT NULL,
  `tipo_profesor` INT NOT NULL,
  PRIMARY KEY (`ID_tipo_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `ID_usuarios` INT NOT NULL,
  `Nickname` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `tipo_usuarios_ID_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`ID_usuarios`),
  INDEX `fk_usuarios_tipo_usuarios1_idx` (`tipo_usuarios_ID_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuarios1`
    FOREIGN KEY (`tipo_usuarios_ID_tipo_usuario`)
    REFERENCES `mydb`.`tipo_usuarios` (`ID_tipo_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `ID_personas` INT NOT NULL,
  `Rut` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Fecha_nacimiento` INT NOT NULL,
  `Correo_electronico` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `usuarios_ID_usuarios` INT NOT NULL,
  PRIMARY KEY (`ID_personas`),
  INDEX `fk_Personas_usuarios1_idx` (`usuarios_ID_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Personas_usuarios1`
    FOREIGN KEY (`usuarios_ID_usuarios`)
    REFERENCES `mydb`.`usuarios` (`ID_usuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`resenas_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resenas_cursos` (
  `ID_Resenas_cursos` INT NOT NULL,
  `calificacion_curso` INT NULL DEFAULT NULL,
  `Resena_curso` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Resenas_cursos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `ID_curso` INT NOT NULL,
  `Duracion_curso` VARCHAR(45) NOT NULL,
  `profesores_ID_profesores` INT NOT NULL,
  `Personas_ID_personas` INT NOT NULL,
  `Resenas_cursos_ID_Resenas_cursos` INT NOT NULL,
  PRIMARY KEY (`ID_curso`),
  INDEX `fk_cursos_Personas1_idx` (`Personas_ID_personas` ASC) VISIBLE,
  INDEX `fk_cursos_Resenas_cursos1_idx` (`Resenas_cursos_ID_Resenas_cursos` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_Personas1`
    FOREIGN KEY (`Personas_ID_personas`)
    REFERENCES `mydb`.`personas` (`ID_personas`),
  CONSTRAINT `fk_cursos_Resenas_cursos1`
    FOREIGN KEY (`Resenas_cursos_ID_Resenas_cursos`)
    REFERENCES `mydb`.`resenas_cursos` (`ID_Resenas_cursos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_pagos` (
  `ID_tipo_pago` INT NOT NULL,
  `tipo_debito` INT NOT NULL,
  `tipo_credito` INT NOT NULL,
  PRIMARY KEY (`ID_tipo_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagos` (
  `ID_pagos` INT NOT NULL,
  `Monto` INT NOT NULL,
  `Fecha_inscripcion` DATE NOT NULL,
  `Tipo_pagos_ID_tipo_pago` INT NOT NULL,
  PRIMARY KEY (`ID_pagos`),
  INDEX `fk_Pagos_Tipo_pagos1_idx` (`Tipo_pagos_ID_tipo_pago` ASC) VISIBLE,
  CONSTRAINT `fk_Pagos_Tipo_pagos1`
    FOREIGN KEY (`Tipo_pagos_ID_tipo_pago`)
    REFERENCES `mydb`.`tipo_pagos` (`ID_tipo_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`inscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inscripciones` (
  `ID_inscripciones` INT NOT NULL,
  `costo_incripcion` INT NOT NULL,
  `alumnos_ID_alumnos` INT NOT NULL,
  `cursos_ID_curso` INT NOT NULL,
  `Pagos_ID_pagos` INT NOT NULL,
  PRIMARY KEY (`ID_inscripciones`, `alumnos_ID_alumnos`, `cursos_ID_curso`),
  INDEX `fk_inscripciones_cursos1_idx` (`cursos_ID_curso` ASC) VISIBLE,
  INDEX `fk_inscripciones_Pagos1_idx` (`Pagos_ID_pagos` ASC) VISIBLE,
  CONSTRAINT `fk_inscripciones_cursos1`
    FOREIGN KEY (`cursos_ID_curso`)
    REFERENCES `mydb`.`cursos` (`ID_curso`),
  CONSTRAINT `fk_inscripciones_Pagos1`
    FOREIGN KEY (`Pagos_ID_pagos`)
    REFERENCES `mydb`.`pagos` (`ID_pagos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`modulos_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modulos_cursos` (
  `ID_modulos_cursos` INT NOT NULL,
  `Modulos_cursos` VARCHAR(60) NOT NULL,
  `Personas_ID_personas` INT NOT NULL,
  `cursos_ID_curso` INT NOT NULL,
  PRIMARY KEY (`ID_modulos_cursos`),
  INDEX `fk_Modulos_cursos_Personas1_idx` (`Personas_ID_personas` ASC) VISIBLE,
  INDEX `fk_Modulos_cursos_cursos1_idx` (`cursos_ID_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Modulos_cursos_cursos1`
    FOREIGN KEY (`cursos_ID_curso`)
    REFERENCES `mydb`.`cursos` (`ID_curso`),
  CONSTRAINT `fk_Modulos_cursos_Personas1`
    FOREIGN KEY (`Personas_ID_personas`)
    REFERENCES `mydb`.`personas` (`ID_personas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`lecciones_modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lecciones_modulos` (
  `ID_Lecciones_modulos` INT NOT NULL,
  `Cantidad_lecciones` INT NOT NULL,
  `Nombre_leccion` VARCHAR(45) NOT NULL,
  `Modulos_cursos_ID_modulos_cursos` INT NOT NULL,
  PRIMARY KEY (`ID_Lecciones_modulos`),
  INDEX `fk_Lecciones_modulos_Modulos_cursos1_idx` (`Modulos_cursos_ID_modulos_cursos` ASC) VISIBLE,
  CONSTRAINT `fk_Lecciones_modulos_Modulos_cursos1`
    FOREIGN KEY (`Modulos_cursos_ID_modulos_cursos`)
    REFERENCES `mydb`.`modulos_cursos` (`ID_modulos_cursos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `agendaviajes` ;

-- -----------------------------------------------------
-- Table `agendaviajes`.`aeropuerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaviajes`.`aeropuerto` (
  `id_aeropuerto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_aeropuerto`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agendaviajes`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaviajes`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agendaviajes`.`destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaviajes`.`destino` (
  `id_destino` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_destino`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agendaviajes`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaviajes`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `pais_origen` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `agendaviajes`.`categoria` (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agendaviajes`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaviajes`.`personas` (
  `rut` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`rut`),
  INDEX `fk_Personas_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Personas_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `agendaviajes`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `agendaviajes`.`viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaviajes`.`viaje` (
  `id_viaje` INT NOT NULL AUTO_INCREMENT,
  `id_destino` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `cantidad_pasajeros` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_origen` INT NOT NULL,
  `id_destino` INT NOT NULL,
  PRIMARY KEY (`id_viaje`),
  INDEX `id_destino` (`id_destino` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_viaje_aeropuerto1_idx` (`id_origen` ASC) VISIBLE,
  INDEX `fk_viaje_aeropuerto2_idx` (`id_destino` ASC) VISIBLE,
  CONSTRAINT `viaje_ibfk_1`
    FOREIGN KEY (`id_destino`)
    REFERENCES `agendaviajes`.`destino` (`id_destino`),
  CONSTRAINT `viaje_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `agendaviajes`.`usuario` (`id_usuario`),
  CONSTRAINT `fk_viaje_aeropuerto1`
    FOREIGN KEY (`id_origen`)
    REFERENCES `agendaviajes`.`aeropuerto` (`id_aeropuerto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viaje_aeropuerto2`
    FOREIGN KEY (`id_destino`)
    REFERENCES `agendaviajes`.`aeropuerto` (`id_aeropuerto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
